name: Snyk Code Scan

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master

      - name: Run Snyk Code test
        run: |
          snyk code test --sarif-file-output=snyk-code.sarif
          ls -lh snyk-code.sarif
          head -20 snyk-code.sarif
        env:
          SNYK_TOKEN: c80a2012-bb87-4482-beb5-399c664f183d

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif

      - name: Snyk Monitor (upload results to Snyk)
        run: snyk monitor
        env:
          SNYK_TOKEN: c80a2012-bb87-4482-beb5-399c664f183d
          

      - name: Upload results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
